window.esdocSearchIndex = [
  [
    "sp-3/src/addcustomer/addcustomer.constants.js~add_cust",
    "variable/index.html#static-variable-ADD_CUST",
    "<span>ADD_CUST</span> <span class=\"search-result-import-path\">SP-3/src/AddCustomer/AddCustomer.Constants.js</span>",
    "variable"
  ],
  [
    "sp-3/src/addcustomer/addcustomer.reducer.js~addcustomer",
    "variable/index.html#static-variable-AddCustomer",
    "<span>AddCustomer</span> <span class=\"search-result-import-path\">SP-3/src/AddCustomer/AddCustomer.Reducer.js</span>",
    "variable"
  ],
  [
    "sp-3/src/viewcustomers/viewcustomer.constants.js~load_customer_success",
    "variable/index.html#static-variable-LOAD_CUSTOMER_SUCCESS",
    "<span>LOAD_CUSTOMER_SUCCESS</span> <span class=\"search-result-import-path\">SP-3/src/ViewCustomers/ViewCustomer.Constants.js</span>",
    "variable"
  ],
  [
    "sp-3/src/routes.js~routes",
    "class/src/routes.js~Routes.html",
    "<span>Routes</span> <span class=\"search-result-import-path\">SP-3/src/routes.js</span>",
    "class"
  ],
  [
    "sp-3/src/stores.js~stores",
    "function/index.html#static-function-Stores",
    "<span>Stores</span> <span class=\"search-result-import-path\">SP-3/src/stores.js</span>",
    "function"
  ],
  [
    "sp-3/src/viewcustomers/viewcustomerreducer.js~viewcustomerreducer",
    "function/index.html#static-function-ViewCustomerReducer",
    "<span>ViewCustomerReducer</span> <span class=\"search-result-import-path\">SP-3/src/ViewCustomers/ViewCustomerReducer.js</span>",
    "function"
  ],
  [
    "sp-3/src/addcustomer/addcustomer.actions.js~addtocustomers",
    "function/index.html#static-function-addToCustomers",
    "<span>addToCustomers</span> <span class=\"search-result-import-path\">SP-3/src/AddCustomer/AddCustomer.Actions.js</span>",
    "function"
  ],
  [
    "sp-3/src/common/fetchjson.js~get_json",
    "function/index.html#static-function-get_json",
    "<span>get_json</span> <span class=\"search-result-import-path\">SP-3/src/Common/fetchJSON.js</span>",
    "function"
  ],
  [
    "sp-3/src/viewcustomers/viewcustomeractions.js~loadcourses",
    "function/index.html#static-function-loadCourses",
    "<span>loadCourses</span> <span class=\"search-result-import-path\">SP-3/src/ViewCustomers/ViewCustomerActions.js</span>",
    "function"
  ],
  [
    "sp-3/src/viewcustomers/viewcustomeractions.js~loadcustomersuccess",
    "function/index.html#static-function-loadCustomerSuccess",
    "<span>loadCustomerSuccess</span> <span class=\"search-result-import-path\">SP-3/src/ViewCustomers/ViewCustomerActions.js</span>",
    "function"
  ],
  [
    "sp-3/src/common/fetchjson.js~post_json",
    "function/index.html#static-function-post_json",
    "<span>post_json</span> <span class=\"search-result-import-path\">SP-3/src/Common/fetchJSON.js</span>",
    "function"
  ],
  [
    "sp-3/src/combined.reducers.js~rootreducer",
    "variable/index.html#static-variable-rootReducer",
    "<span>rootReducer</span> <span class=\"search-result-import-path\">SP-3/src/combined.reducers.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/addcustomer/addcustomer.actions.js",
    "file/src/AddCustomer/AddCustomer.Actions.js.html",
    "src/AddCustomer/AddCustomer.Actions.js",
    "file"
  ],
  [
    "src/addcustomer/addcustomer.constants.js",
    "file/src/AddCustomer/AddCustomer.Constants.js.html",
    "src/AddCustomer/AddCustomer.Constants.js",
    "file"
  ],
  [
    "src/addcustomer/addcustomer.reducer.js",
    "file/src/AddCustomer/AddCustomer.Reducer.js.html",
    "src/AddCustomer/AddCustomer.Reducer.js",
    "file"
  ],
  [
    "src/common/fetchjson.js",
    "file/src/Common/fetchJSON.js.html",
    "src/Common/fetchJSON.js",
    "file"
  ],
  [
    "src/viewcustomers/viewcustomer.constants.js",
    "file/src/ViewCustomers/ViewCustomer.Constants.js.html",
    "src/ViewCustomers/ViewCustomer.Constants.js",
    "file"
  ],
  [
    "src/viewcustomers/viewcustomeractions.js",
    "file/src/ViewCustomers/ViewCustomerActions.js.html",
    "src/ViewCustomers/ViewCustomerActions.js",
    "file"
  ],
  [
    "src/viewcustomers/viewcustomerreducer.js",
    "file/src/ViewCustomers/ViewCustomerReducer.js.html",
    "src/ViewCustomers/ViewCustomerReducer.js",
    "file"
  ],
  [
    "src/combined.reducers.js",
    "file/src/combined.reducers.js.html",
    "src/combined.reducers.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.test.js",
    "file/src/index.test.js.html",
    "src/index.test.js",
    "file"
  ],
  [
    "src/routes.js",
    "file/src/routes.js.html",
    "src/routes.js",
    "file"
  ],
  [
    "src/routes.js~routes#render",
    "class/src/routes.js~Routes.html#instance-method-render",
    "src/routes.js~Routes#render",
    "method"
  ],
  [
    "src/stores.js",
    "file/src/stores.js.html",
    "src/stores.js",
    "file"
  ]
]