window.esdocSearchIndex = [
  [
    "sampleproject/src/addcustomer/addcustomer.constants.js~add_customer",
    "variable/index.html#static-variable-ADD_CUSTOMER",
    "<span>ADD_CUSTOMER</span> <span class=\"search-result-import-path\">SampleProject/src/AddCustomer/AddCustomer.Constants.js</span>",
    "variable"
  ],
  [
    "sampleproject/src/addcustomer/addcustomer.constants.js~add_customer_service",
    "variable/index.html#static-variable-ADD_CUSTOMER_SERVICE",
    "<span>ADD_CUSTOMER_SERVICE</span> <span class=\"search-result-import-path\">SampleProject/src/AddCustomer/AddCustomer.Constants.js</span>",
    "variable"
  ],
  [
    "sampleproject/src/viewcustomers/viewcustomer.constants.js~customers_list_service",
    "variable/index.html#static-variable-CUSTOMERS_LIST_SERVICE",
    "<span>CUSTOMERS_LIST_SERVICE</span> <span class=\"search-result-import-path\">SampleProject/src/ViewCustomers/ViewCustomer.Constants.js</span>",
    "variable"
  ],
  [
    "sampleproject/src/viewcustomers/viewcustomer.constants.js~recieve_customers",
    "variable/index.html#static-variable-RECIEVE_CUSTOMERS",
    "<span>RECIEVE_CUSTOMERS</span> <span class=\"search-result-import-path\">SampleProject/src/ViewCustomers/ViewCustomer.Constants.js</span>",
    "variable"
  ],
  [
    "sampleproject/src/viewcustomers/viewcustomer.actions.js~recievecustomerlist",
    "function/index.html#static-function-RecieveCustomerList",
    "<span>RecieveCustomerList</span> <span class=\"search-result-import-path\">SampleProject/src/ViewCustomers/ViewCustomer.Actions.js</span>",
    "function"
  ],
  [
    "sampleproject/src/routes.js~routes",
    "class/src/routes.js~Routes.html",
    "<span>Routes</span> <span class=\"search-result-import-path\">SampleProject/src/routes.js</span>",
    "class"
  ],
  [
    "sampleproject/src/stores.js~stores",
    "function/index.html#static-function-Stores",
    "<span>Stores</span> <span class=\"search-result-import-path\">SampleProject/src/stores.js</span>",
    "function"
  ],
  [
    "sampleproject/src/addcustomer/addcustomer.actions.js~addcustomer",
    "function/index.html#static-function-addCustomer",
    "<span>addCustomer</span> <span class=\"search-result-import-path\">SampleProject/src/AddCustomer/AddCustomer.Actions.js</span>",
    "function"
  ],
  [
    "sampleproject/src/addcustomer/addcustomer.reducer.js~addcustomer",
    "variable/index.html#static-variable-addCustomer",
    "<span>addCustomer</span> <span class=\"search-result-import-path\">SampleProject/src/AddCustomer/AddCustomer.Reducer.js</span>",
    "variable"
  ],
  [
    "sampleproject/src/addcustomer/addcustomer.actions.js~addtocustomers",
    "function/index.html#static-function-addToCustomers",
    "<span>addToCustomers</span> <span class=\"search-result-import-path\">SampleProject/src/AddCustomer/AddCustomer.Actions.js</span>",
    "function"
  ],
  [
    "sampleproject/src/viewcustomers/viewcustomer.actions.js~fetchcustomers",
    "function/index.html#static-function-fetchCustomers",
    "<span>fetchCustomers</span> <span class=\"search-result-import-path\">SampleProject/src/ViewCustomers/ViewCustomer.Actions.js</span>",
    "function"
  ],
  [
    "sampleproject/src/common/api.js~requestget",
    "function/index.html#static-function-requestGet",
    "<span>requestGet</span> <span class=\"search-result-import-path\">SampleProject/src/Common/Api.js</span>",
    "function"
  ],
  [
    "sampleproject/src/common/api.js~requestpost",
    "function/index.html#static-function-requestPost",
    "<span>requestPost</span> <span class=\"search-result-import-path\">SampleProject/src/Common/Api.js</span>",
    "function"
  ],
  [
    "sampleproject/src/combined.reducers.js~rootreducer",
    "variable/index.html#static-variable-rootReducer",
    "<span>rootReducer</span> <span class=\"search-result-import-path\">SampleProject/src/combined.reducers.js</span>",
    "variable"
  ],
  [
    "sampleproject/src/viewcustomers/viewcustomer.reducer.js~viewcustomerreducer",
    "function/index.html#static-function-viewCustomerReducer",
    "<span>viewCustomerReducer</span> <span class=\"search-result-import-path\">SampleProject/src/ViewCustomers/ViewCustomer.Reducer.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/addcustomer/addcustomer.actions.js",
    "file/src/AddCustomer/AddCustomer.Actions.js.html",
    "src/AddCustomer/AddCustomer.Actions.js",
    "file"
  ],
  [
    "src/addcustomer/addcustomer.constants.js",
    "file/src/AddCustomer/AddCustomer.Constants.js.html",
    "src/AddCustomer/AddCustomer.Constants.js",
    "file"
  ],
  [
    "src/addcustomer/addcustomer.reducer.js",
    "file/src/AddCustomer/AddCustomer.Reducer.js.html",
    "src/AddCustomer/AddCustomer.Reducer.js",
    "file"
  ],
  [
    "src/common/api.js",
    "file/src/Common/Api.js.html",
    "src/Common/Api.js",
    "file"
  ],
  [
    "src/viewcustomers/viewcustomer.actions.js",
    "file/src/ViewCustomers/ViewCustomer.Actions.js.html",
    "src/ViewCustomers/ViewCustomer.Actions.js",
    "file"
  ],
  [
    "src/viewcustomers/viewcustomer.constants.js",
    "file/src/ViewCustomers/ViewCustomer.Constants.js.html",
    "src/ViewCustomers/ViewCustomer.Constants.js",
    "file"
  ],
  [
    "src/viewcustomers/viewcustomer.reducer.js",
    "file/src/ViewCustomers/ViewCustomer.Reducer.js.html",
    "src/ViewCustomers/ViewCustomer.Reducer.js",
    "file"
  ],
  [
    "src/combined.reducers.js",
    "file/src/combined.reducers.js.html",
    "src/combined.reducers.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.test.js",
    "file/src/index.test.js.html",
    "src/index.test.js",
    "file"
  ],
  [
    "src/routes.js",
    "file/src/routes.js.html",
    "src/routes.js",
    "file"
  ],
  [
    "src/routes.js~routes#render",
    "class/src/routes.js~Routes.html#instance-method-render",
    "src/routes.js~Routes#render",
    "method"
  ],
  [
    "src/stores.js",
    "file/src/stores.js.html",
    "src/stores.js",
    "file"
  ]
]